//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCFLY
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public int DeptId { get; set; }
        public string EmpID { get; set; }
        public string IT { get; set; }
        public string Accounting { get; set; }
        public string Maintence { get; set; }
        public int HoursHoursID { get; set; }
    
        public virtual Hours Hour { get; set; }
    }
}
