//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCFLY
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.Hours = new HashSet<Hours>();
        }
    
        public int EmpID { get; set; }
        public string Name { get; set; }
        public string Location { get; set; }
        public string SSN { get; set; }
        public string Phone { get; set; }
    
        public virtual ICollection<Hours> Hours { get; set; }
    }
}
