//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCFLY
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hours
    {
        public Hours()
        {
            this.Departments = new HashSet<Department>();
        }
    
        public int HoursID { get; set; }
        public string DepID { get; set; }
        public string Vacation { get; set; }
        public string OT { get; set; }
        public string RegHours { get; set; }
        public string Holiday { get; set; }
        public int EmployeeEmpID { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual ICollection<Department> Departments { get; set; }
    }
}
